#include "fm_web.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "esp_http_server.h"
#include "mbedtls/base64.h"
#include "sdkconfig.h"
#include "fm_control.h"
static const char PAGE[]="<!doctype html><meta name=viewport content='width=device-width,initial-scale=1'><style>body{font-family:sans-serif;background:#f3f6fa;color:#092047;max-width:600px;margin:auto;padding:14px}.c{background:white;padding:18px;border-radius:14px}input,button{width:100%;padding:15px;margin:7px 0;box-sizing:border-box;font-size:18px}button{background:#087cff;color:white;border:0;border-radius:9px}.off{background:#cf2634}</style><h2>SIGNAL WAVE FM TX</h2><div class=c><p id=s>---</p><input id=f type=number min=76 max=108 step=.1 value=92><input id=k type=number min=10 max=20 step=.01 value=15><button onclick=setf()>周波数設定</button><button class=off onclick=rf(0)>RF OFF</button><button onclick=rf(1)>RF ON（実機確認後）</button><button onclick=save()>Flash保存</button></div><script>async function q(u){let r=await fetch(u),x=await r.json();if(!r.ok)throw Error(x.error||r.status);return x}async function poll(){try{let x=await q('/api/status');s.textContent=`${(x.frequency_khz/1000).toFixed(1)} MHz / KIDX ${x.kidx} / ${x.state} / PLL ${x.pll_lock?'LOCK':'UNLOCK'} / FPGA ${x.fpga_ok?'OK':'NG'} / RF ${x.rf_on?'ON':'OFF'}`+(x.detail?` / ${x.detail}`:'')}catch(e){s.textContent=e}}async function setf(){try{await q(`/api/set?f=${f.value}&kv=${k.value}`)}catch(e){alert(e)}}async function rf(x){try{await q('/api/rf?on='+x)}catch(e){alert(e)}}async function save(){try{await q('/api/save')}catch(e){alert(e)}}poll();setInterval(poll,1000)</script>";
static bool auth(httpd_req_t*r){char got[160]={0},raw[96],want[160]="Basic ";snprintf(raw,sizeof(raw),"%s:%s",CONFIG_FM_WEB_USER,CONFIG_FM_WEB_PASSWORD);size_t n=0;mbedtls_base64_encode((unsigned char*)want+6,sizeof(want)-7,&n,(unsigned char*)raw,strlen(raw));want[6+n]=0;if(httpd_req_get_hdr_value_str(r,"Authorization",got,sizeof(got))==ESP_OK&&!strcmp(got,want))return true;httpd_resp_set_status(r,"401 Unauthorized");httpd_resp_set_hdr(r,"WWW-Authenticate","Basic realm=\"FM Transmitter\"");httpd_resp_send(r,NULL,0);return false;}
static esp_err_t root(httpd_req_t*r){if(!auth(r))return ESP_OK;httpd_resp_set_type(r,"text/html; charset=utf-8");return httpd_resp_send(r,PAGE,HTTPD_RESP_USE_STRLEN);}
static esp_err_t api(httpd_req_t*r){if(!auth(r))return ESP_OK;fm_status_t s;esp_err_t e=ESP_OK;char q[128]={0},v[24]={0};size_t n=httpd_req_get_url_query_len(r)+1;if(n>1&&n<=sizeof(q))httpd_req_get_url_query_str(r,q,sizeof(q));if(!strcmp(r->uri,"/api/set")){httpd_query_key_value(q,"f",v,sizeof(v));double f=strtod(v,NULL);httpd_query_key_value(q,"kv",v,sizeof(v));e=fm_control_set(lround(f*1000),lround(strtod(v,NULL)*100),true);}else if(!strcmp(r->uri,"/api/rf")){httpd_query_key_value(q,"on",v,sizeof(v));e=fm_control_set_rf(!strcmp(v,"1"));}else if(!strcmp(r->uri,"/api/save"))e=fm_control_save();fm_control_get(&s);static const char *const STATE[]={"BOOT","TUNED","FAULT"};char b[384];snprintf(b,sizeof(b),"{\"frequency_khz\":%lu,\"kv_centi\":%u,\"kidx\":%u,\"state\":\"%s\",\"pll_lock\":%s,\"fpga_ok\":%s,\"rf_on\":%s,\"detail\":\"%s\"%s}",(unsigned long)s.frequency_khz,s.kv_centi,s.kidx,STATE[s.state],s.pll_lock?"true":"false",s.fpga_ok?"true":"false",s.rf_on?"true":"false",s.error,e==ESP_OK?"":",\"error\":\"request rejected\"");if(e!=ESP_OK)httpd_resp_set_status(r,"400 Bad Request");httpd_resp_set_type(r,"application/json");return httpd_resp_sendstr(r,b);}
esp_err_t fm_web_start(void){httpd_handle_t h=NULL;httpd_config_t c=HTTPD_DEFAULT_CONFIG();esp_err_t e=httpd_start(&h,&c);if(e!=ESP_OK)return e;httpd_uri_t u[]={{.uri="/",.method=HTTP_GET,.handler=root},{.uri="/api/status",.method=HTTP_GET,.handler=api},{.uri="/api/set",.method=HTTP_GET,.handler=api},{.uri="/api/rf",.method=HTTP_GET,.handler=api},{.uri="/api/save",.method=HTTP_GET,.handler=api}};for(unsigned i=0;i<sizeof(u)/sizeof(u[0]);i++)ESP_ERROR_CHECK(httpd_register_uri_handler(h,&u[i]));return ESP_OK;}
